time_track/urls.py
from django.urls import path, reverse_lazy
from .views import TimeTrackView, DeleteTimeTrack, AddTimeTrack

app_name = "TimeTrack"
urlpatterns = [
   path('delete_track/<pk>/', DeleteTimeTrack.as_view(), name='delete'),
   path('add_track/', AddTimeTrack.as_view(), name='add'),
   path('<monday_date>/', TimeTrackView.as_view(), name='main'),
]

time_track/models.py
from django.db import models

# Create your models here.
class TimeTrack(models.Model):
   PRODUCTIVITY_LEVEL = [("Productive", "Productive"), ("Unproductive", "Unproductive"), ("Neutral", "Neutral")]
   time = models.PositiveIntegerField()
   name = models.CharField(max_length=50)
   level = models.CharField(choices=PRODUCTIVITY_LEVEL, max_length=20)
   date_for = models.DateField(default=None)

   def __str__(self):
      hour = self.time // 60
      minutes = self.time % 60
      return f"{self.name} | {hour} hour {minutes} minutes | {self.level}"
   

time_track/forms.py
from django import forms
from.models import TimeTrack

class NewTimeTracks(forms.ModelForm):
   class Meta:
      model = TimeTrack
      fields = ['name', 'level', 'time']
      widgets = {
         'name': forms.TextInput(attrs={
            'class': 'block w-[400px] bg-transparent border border-slate-700 rounded-sm p-2 text-sm outline-none',
         }),
         'time': forms.NumberInput(attrs={
            'class': 'block w-[400px] bg-transparent border border-slate-700 rounded-sm p-2 text-sm outline-none',
         }),
         'level': forms.HiddenInput()
      }

time_track/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from datetime import date, timedelta, datetime
from .models import TimeTrack
from .forms import NewTimeTracks
import json

# Create your views here.
class TimeTrackView(View, LoginRequiredMixin):
   template_name = 'time_track/index.html'

   def proccess_date_url(self, monday_date):
      arr_date = monday_date.split('-')
      return date(int(arr_date[0]), int(arr_date[1]), int(arr_date[2]))

   def get(self, request, monday_date):
      date_url = self.proccess_date_url(monday_date)
      arr_result = []
      is_today_in_thisweek = False
      last_week = date_url - timedelta(days=7)
      next_week = date_url + timedelta(days=7)
      for x in range(0, 7):
         date_appended = date_url + timedelta(days=x)
         if date_appended == date.today():
            is_today_in_thisweek = True
            next_week = None
         arr_result.append({
            'date': date_appended,
            'tracks': [
               ('Productive', TimeTrack.objects.order_by('level').filter(date_for=date_appended, level="Productive")),
               ('Unproductive', TimeTrack.objects.order_by('level').filter(date_for=date_appended, level="Unproductive")),
               ('Neutral', TimeTrack.objects.order_by('level').filter(date_for=date_appended, level="Neutral"))
            ]
         })

      return render(request, self.template_name, {
         'time_tracks': arr_result,
         'is_today_in_thisweek': is_today_in_thisweek,
         'last_week': last_week,
         'next_week': next_week,
         'form': NewTimeTracks,
         'today_index': date.today().weekday()
      })


class DeleteTimeTrack(View, LoginRequiredMixin):
   model = TimeTrack

   def get(self, request, pk):
      self.model.objects.filter(id=pk).delete()
      monday_date = (date.today() - timedelta(days=date.today().weekday())).strftime('%Y-%m-%d')
      return redirect('TimeTrack:main', monday_date=monday_date)

class AddTimeTrack(View, LoginRequiredMixin):
   def post(self, request):
      form = NewTimeTracks(request.POST)
      if form.is_valid():
         time_track = form.save(commit=False)
         time_track.date_for = datetime.strptime(request.POST['date_for'], '%Y-%m-%d').date()
         time_track.save()

         message_dict = {
            'title': 'Track has been created',
            'content': f'Your track has been successfully added on ' + time_track.date_for.strftime('%#d %B %Y')
         }
         messages.success(request, json.dumps(message_dict))
      else:
         print(form.errors)
         message_dict = {
            'title': 'Track failed to be added',
            'content': f'Please try again and make sure everything is set perfectly'
         }
         messages.error(request, json.dumps(message_dict))

      monday_date = (date.today() - timedelta(days=date.today().weekday())).strftime('%Y-%m-%d')
      return redirect('TimeTrack:main', monday_date=monday_date)

templates/time_track/index.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}

{% load static %}
{% load custom_tags %}

<div class="w-11/12 md:w-5/6 mx-auto py-28">
   <div class="mb-10 mt-4">
      <h1 class="font-semibold">
         <span class="text-3xl md:text-4xl">Time Track</span> 
         <span class="block md:inline text-xl md:text-2xl text-slate-300 md:pl-5 mt-2">21 August 2023 - 27 August 2023</span>
      </h1>
      <div class="flex gap-5 mt-7">
         <a href="{% url 'TimeTrack:main' last_week|date:'Y-m-d' %}" class="flex justify-center items-center gap-3 w-[175px] bg-slate-700 rounded-sm py-2 text-sm text-slate-200 transition-all hover:scale-[1.01] hover:bg-[#3a4b61] hover:text-white">
            <img src="{% static 'image/arrow.png' %}" class="w-3 filter-to-white rotate-180">
            <span>Previous Week</span>
         </a>
         {% if not is_today_in_thisweek %}
         <a href="{% url 'TimeTrack:main' next_week|date:'Y-m-d' %}" class="flex justify-center items-center gap-3 w-[175px] bg-slate-700 rounded-sm py-2 text-sm text-slate-200 transition-all hover:scale-[1.01] hover:bg-[#3a4b61] hover:text-white">
            <span>Next Week</span>
            <img src="{% static 'image/arrow.png' %}" class="w-3 filter-to-white">
         </a>
         {% endif %}
      </div>
   </div>

   <div class="mb-5 text-sm">
      <p class="font-semibold">Shift + Scroll to scroll left and right</p>
      <p>Click the name of activity to delete the tracks</p>
   </div>
   <div>
      <div class="flex justify-between mb-5" id="scroll_helper">
         <div class="flex items-center gap-3">
            <button type="button" class="bg-slate-800 px-5 md:px-8 py-2 border transition-all border-slate-600 shadow-xl text-sm hover:bg-[#233045]" data-scroll-direction="start">Start</button>
            <button type="button" class="bg-slate-800 px-5 md:px-8 py-2 border transition-all border-slate-600 shadow-xl hover:pl-5 hover:pr-[44px]" data-scroll-direction="left"><img src="{% static 'image/arrow.png' %}" class="w-4 md:w-5 filter-to-white rotate-180"></button>
         </div>
         <div class="flex items-center gap-3">
            <button type="button" class="bg-slate-800 px-5 md:px-8 py-2 border transition-all border-slate-600 shadow-xl hover:pr-5 hover:pl-[44px]" data-scroll-direction="right"><img src="{% static 'image/arrow.png' %}" class="w-4 md:w-5 filter-to-white"></button>
            <button type="button" class="bg-slate-800 px-5 md:px-8 py-2 border transition-all border-slate-600 shadow-xl text-sm hover:bg-[#233045]" data-scroll-direction="end">End</button>
         </div>
      </div>
      <div class="relative">
         <div class="absolute top-0 left-0 h-full w-[50px] md:w-[100px] z-10 hidden justify-start items-center bg-gradient-to-r from-slate-900 to-transparent" id="fade_gradient_left"></div>
         <div class="flex gap-5 overflow-auto hide-scrollbar scroll-smooth" id="track_wrapper">
            {% for time in time_tracks %}
            <div class="w-[330px] md:w-[370px] flex-shrink-0 bg-slate-800 border border-slate-700 rounded-xl mx-auto sm:mx-0 mb-3 p-2 shadow-3xl transition-all hover:bg-[#222f44] relative">
               <div class="border-b border-slate-600 p-5">
                  <h2 class="font-bold text-2xl">{{ time.date|date:'l' }}</h2>
                  <p class="text-slate-300 italic">{{ time.date|date:'j F Y' }}</p>
               </div>
               <div class="p-5 mb-12">
                  <h2 class="font-bold text-lg mb-2">Time Spent</h2>
                  {% for tracks in time.tracks %}
                  <div class="mb-3 text-sm text-slate-100">
                     <h3 class="font-semibold text-base">{{ tracks.0 }}: <span class="text-xs text-slate-300 total_time_placeholder">{{ tracks.1|total_time }}</span></h3>
                     <div class="track_placeholder">
                        {% for track in tracks.1 %}
                        <p>
                           <a class="hover:text-red-300 cursor-pointer" href="{% url 'TimeTrack:delete' track.id %}">{{ track.name }}: </a>
                           <span class="text-slate-300 time_span">{{ track.time }}</span><span> minutes</span>
                        </p>
                        {% endfor %}
                     </div>
                     {% if tracks.1|length == 0 %}
                     <p class="font-bold text-lg">-</p>
                     {% endif %}
                  </div>
                  {% endfor %}
                  {% if forloop.counter0 == today_index or forloop.counter == today_index %}
                  <button class="absolute left-7 bottom-7 bg-slate-700 rounded-sm px-10 py-2 text-sm text-slate-200 transition-all hover:scale-[1.01] hover:bg-slate-600 hover:text-white add_time_track_button" data-date="{{ time.date|date:'Y-m-d' }}">Add New Tracks</button>
                  {% endif %}
               </div>
            </div>
            {% endfor %}
         </div>
         <div class="absolute top-0 right-0 h-full w-[50px] md:w-[100px] flex justify-end items-center bg-gradient-to-l from-slate-900 to-transparent" id="fade_gradient_right"></div>
      </div>
   </div>
</div>

{% include 'time_track/new_tracks.html' %}

{% endblock %}

templates/time_track/new_tracks.html
<div class="hidden items-center justify-center fixed top-0 left-0 w-full min-h-screen z-[100]" id="add_time_track_form_wrapper">
   <div class="fixed top-0 left-0 w-full h-full bg-neutral-900 opacity-0 shadow-box-hover transition-all" id="dark_bg"></div>
   <div class="z-10 bg-slate-800 rounded-xl px-10 py-14 scale-[0.85] opacity-0 transition-all duration-300" id="main_form">
      <form action="{% url 'TimeTrack:add' %}" method="POST">
         {% csrf_token %}
         <h2 class="font-semibold text-2xl mb-5">New Tracks</h2>
         <input type="text" class="hidden" name="date_for">
         <div class="mb-4">
            <label for="{{ form.id_for_name }}" class="text-sm pb-1">Name: </label>
            {{ form.name }}
         </div>
         <div class="mb-4">
            <label for="{{ form.id_for_time }}" class="text-sm pb-1">Minutes: </label>
            {{ form.time }}
         </div>
         <div class="mb-7">
            <label class="text-sm pb-1">Productivity Level: </label>
            {{ form.level }}
            <div class="relative">
               <p class="block w-[400px] bg-transparent border border-slate-700 rounded-sm p-2 text-sm cursor-pointer"
                  id="time_track_form_input">Select Level</p>
               <div
                  class="hidden absolute top-full left-0 bg-slate-800 w-[400px] -translate-y-5 opacity-0 cursor-pointer transition-all duration-300"
                  id="time_track_form_select">
                  <span class="block w-full text-sm p-3 border-b border-slate-700">Productive</span>
                  <span class="block w-full text-sm p-3 border-b border-slate-700">Unproductive</span>
                  <span class="block w-full text-sm p-3 border-b border-slate-700">Neutral</span>
               </div>
            </div>
         </div>
         <div>
            <button
               class="bg-[#2e3f5b] rounded-sm px-10 py-2 text-sm text-slate-200 transition-all hover:scale-[1.01] hover:bg-[#3e5479] hover:text-white">Track</button>
            <button
               class="bg-slate-700 rounded-sm ml-2 px-10 py-2 text-sm text-slate-200 transition-all hover:scale-[1.01] hover:bg-slate-600 hover:text-white"
               type="button">Cancel</button>
         </div>
      </form>
   </div>
</div>