habit_track/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import HabitIndexPage, HabitTrackingPage, CheckHabit

app_name = "Habit"
urlpatterns = [
   path('', HabitIndexPage.as_view(), name="main"),
   path('<str:username>/<str:slug>/check_habit', CheckHabit.as_view(), name='check_habit'),
   path('<str:username>/<str:slug>/<start_date>', HabitTrackingPage.as_view(), name="tracking_page")
]

time_track/urls.py
from django.urls import path, reverse_lazy
from .views import TimeTrackView, DeleteTimeTrack, AddTimeTrack

app_name = "TimeTrack"
urlpatterns = [
   path('delete_track/<pk>/', DeleteTimeTrack.as_view(), name='delete'),
   path('add_track/', AddTimeTrack.as_view(), name='add'),
   path('<monday_date>/', TimeTrackView.as_view(), name='main'),
]

habit_track/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Habit(models.Model):
   name         = models.CharField(max_length=100)
   description  = models.TextField()
   habit_type   = models.CharField(max_length=50)
   updated_at   = models.DateTimeField(default=datetime.today())
   created_at   = models.DateTimeField(auto_now_add=True)
   user         = models.ForeignKey(User, on_delete=models.CASCADE)

   def __str__(self):
      return f"{self.name} ({self.habit_type})"

class HabitCheck(models.Model):
   day_num = models.IntegerField()
   habit = models.ForeignKey(Habit, on_delete=models.CASCADE)

   def __str__(self):
      return f"Day {self.day_num}, {self.habit.name} | {self.habit.user.username}"
   

habit_track/forms.py
from django import forms
from .models import Habit

class CreateHabitForm(forms.ModelForm):
   class Meta:
      model = Habit
      fields = ['name', 'description', 'habit_type']
      widgets = {
         'name': forms.TextInput(attrs={
            'class': 'w-full bg-transparent border border-slate-600 rounded-sm mt-2 mb-1 p-2 text-sm outline-none'
         }),
         'description': forms.Textarea(attrs={
            'class': 'w-full bg-transparent border border-slate-600 rounded-sm mt-2 mb-1 p-2 text-sm outline-none resize-none',
            'rows': 5
         }),
         'habit_type': forms.TextInput(attrs={
            'class': 'hidden'
         }),
      }

class DescriptionForm(forms.ModelForm):
   class Meta:
      model = Habit
      fields = ['description']
      widgets = {
         'description': forms.Textarea(attrs={
            'class': 'w-2/3 block bg-transparent border border-slate-600 rounded-sm mt-2 mb-1 p-2 text-sm outline-none resize-none',
            'rows': 5
         })
      }

habit_track/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .models import Habit, HabitCheck
from .forms import CreateHabitForm, DescriptionForm
from datetime import date, timedelta, datetime
import json, math, calendar

# Create your views here.
class HabitIndexPage(View, LoginRequiredMixin):
   template_name = "habit_tracks/index.html"
   context = {
      'monday': date.today() - timedelta(days=date.today().weekday())
   }

   def get(self, request):
      self.context['habits'] = Habit.objects.filter(user=request.user).order_by('-created_at').values()
      self.context['form'] = CreateHabitForm
      return render(request, self.template_name, self.context)

   def post(self, request):
      form = CreateHabitForm(request.POST, initial={'user': request.user})
      if form.is_valid():
         habit = form.save(commit=False)
         habit.user = request.user
         habit.save()

         message_dict = {
            'title': 'Habit To Track Created',
            'content': f'You can now track your habit ({form.cleaned_data["name"]}). Wish you all the best 🤞'
         }
         messages.success(request, json.dumps(message_dict))

         return redirect('Habit:main')

      self.context['form'] = form

      return render(request, self.template_name, self.context)

class HabitTrackingPage(DetailView, LoginRequiredMixin):
   template_name = 'habit_tracks/tracking_page.html'
   model = Habit
   slug_field = 'name'
   context_object_name = 'habit_tracked'
   start_time = None
   timeframe_type = None

   def get_start_date(self, start_date):
      arr = start_date.split('-')
      if len(arr) == 3:
         self.timeframe_type = 'Weekly'
         start_date = int(arr[2])
      else:
         self.timeframe_type = 'Monthly'
         start_date = 1

      return date(int(arr[0]), int(arr[1]), start_date)

   def get_queryset(self):
      querysets = super().get_queryset()
      # initial the start_time variable
      self.start_time = self.get_start_date(self.kwargs['start_date'])
      return querysets

   def get_weekly_menu(self, created_habit_time):
      # day index in template
      today_day_index = (6 - date.today().weekday())
      create_day_index = created_habit_time.weekday()

      # get created time and today
      start_day = created_habit_time - timedelta(days=create_day_index)
      end_day = date.today() + timedelta(days=today_day_index)
      total_week = ( (end_day - start_day).days + 1 ) // 7

      # returning monday and sunday time
      arr_result = []
      for i in range(0, total_week):
         arr_result.append({
            'monday': start_day + timedelta(days=(i*7)),
            'sunday': start_day + timedelta(days=( ((i+1)*7) - 1) )
         },)

      arr_result.reverse()
      
      return arr_result
   
   def get_monthly_menu(self, created_habit_time):
      # find year and month difference and total month difference
      year_difference = (date.today().year - created_habit_time.year)
      month_difference = (date.today().month - created_habit_time.month)
      total_month = year_difference * 12 + month_difference + 1

      # append all monthly menu
      arr_result = []
      for i in range(0, total_month):
         appended_year = created_habit_time.year + math.floor((created_habit_time.month + i) / 12)
         appended_month = created_habit_time.month + i
         # if it's more than 1 year
         while appended_month > 12:
            appended_month -= 12
         arr_result.append(date(appended_year, appended_month, 1))

      arr_result.reverse()

      return arr_result

   def get_today_index(self, get_type):
      if get_type == 'Weekly':
         start_time_timeframe = (date.today() - self.start_time).days
         if (start_time_timeframe ** 2) / 7 < 7:
            # set index in template
            return date.today().weekday()
         else:
            # no today index
            return 10
      elif get_type == 'Monthly':
         tday = date.today()
         if self.start_time.month != tday.month:
            return 100
         else:
            return tday.day - 1

   def get_checks_data(self, created_habit_time, habit, day_range):
      arr_result = []
      day_num_start = (self.start_time - created_habit_time).days + 1
      arr_result.append(day_num_start)
      arr_result.append(HabitCheck.objects.\
                              filter(habit=habit).\
                              filter(day_num__gte=day_num_start, day_num__lte=day_num_start + day_range).\
                              values_list('day_num', flat=True))
      arr_result.append(self.get_today_index(self.timeframe_type))

      return arr_result

   def get_current_timeframe(self, timeframe):
      if timeframe == 'Weekly':
         sunday_date = self.start_time + timedelta(days=6)
         from_date = self.start_time.strftime('%#d %B %Y')
         until_date = sunday_date.strftime('%#d %B %Y')
         return f"{from_date} - {until_date}"
      else:
         return self.start_time.strftime('%B %Y')

   def is_checked(self, habit):
      habit_create_time = date(habit.updated_at.year, habit.updated_at.month, habit.updated_at.day)
   
      if habit_create_time == date.today():
         return True
      else:
         return False



   def get_context_data(self, *args, **kwargs):
      kwargs = super().get_context_data(*args, **kwargs)
      habit = kwargs['habit_tracked']
      kwargs['timeframe_type'] = self.timeframe_type
      kwargs['today_timeframe'] = date.today() - timedelta(days=date.today().weekday())
      kwargs['is_checked'] = self.is_checked(habit)

      # get form
      kwargs['form'] = DescriptionForm(initial={
         'description': habit.description
      })

      # get the menu's
      kwargs['current_timeframe'] = self.get_current_timeframe(self.timeframe_type)
      create_time = habit.created_at
      created_habit_time = date(create_time.year, create_time.month, create_time.day)
      kwargs['weekly_menu'] = self.get_weekly_menu(created_habit_time)
      kwargs['monthly_menu'] = self.get_monthly_menu(created_habit_time)

      # get checks data
      if self.timeframe_type == 'Weekly':
         checks_data = self.get_checks_data(created_habit_time,  habit, 6)
      elif self.timeframe_type == 'Monthly':
         number_of_days_in_month = calendar.monthrange(self.start_time.year, self.start_time.month)[1]
         checks_data = self.get_checks_data(created_habit_time,  habit, number_of_days_in_month - 1)
      kwargs['day_num_start'] = checks_data[0]
      kwargs['habit_checks'] = checks_data[1]
      kwargs['today_day_index'] = checks_data[2]
      
      return kwargs
   
   def post(self, request, *args, **kwargs):
      form = DescriptionForm(request.POST)

      if form.is_valid():
         habit = Habit.objects.filter(name=kwargs['slug']).first()
         habit.description = form.cleaned_data['description']
         habit.save()
         
         message_dict = {
            'title': 'Habit Edited',
            'content': f'Description is successfully edited!'
         }
         messages.error(request, json.dumps(message_dict))
      else:
         message_dict = {
            'title': 'Edit Failed',
            'content': f'Description is not valid! Please re-check your input!'
         }
         messages.error(request, json.dumps(message_dict))

      
      return redirect('Habit:tracking_page', **kwargs)


class CheckHabit(View, LoginRequiredMixin):
   http_method_names = ['delete', 'post']

   def save_habit_checks(self, post_data, habit, habit_check, day_num):
      if 'check' in post_data:
         if not habit_check:
            new_check = HabitCheck(habit=habit, day_num=day_num)
            new_check.save()
            return True
      elif 'uncheck' in post_data:
         if habit_check:
            habit_check.delete()
            
      return False


   def save_habit_data(self, habit, day_num, habit_created_date):
      today_day_num = (date.today() - habit_created_date).days + 1
      if today_day_num == int(day_num):
         habit.updated_at = datetime.today()
         habit.save()
   
   def post(self, request, *args, **kwargs):
      day_num = request.POST['day_num']
      if int(day_num) >= 1:
         habit = Habit.objects.filter(user=request.user, name=kwargs['slug']).first()
         habit_created_date = date(habit.created_at.year, habit.created_at.month, habit.created_at.day)
         habit_check = HabitCheck.objects.filter(habit=habit, day_num=day_num).first()

         # create or delete habit checks
         if self.save_habit_checks(request.POST, habit, habit_check, day_num):
            message_dict = {
               'date': ( habit_created_date + timedelta(days=int(day_num)-1) ).strftime('%#d %B %Y')
            }
            messages.success(request, json.dumps(message_dict))

         # edit updated_at when we check on current date
         self.save_habit_data(habit, day_num, habit_created_date)
      else:
         message_dict = {
            'title': 'Check Failed',
            'content': f'Please try again!'
         }
         messages.error(request, json.dumps(message_dict))

      returned_start_time = date.today() - timedelta(days=date.today().weekday())
      if 'is_monthly' in request.POST:
         kwargs['start_date'] = returned_start_time.strftime('%Y-%m')
      else:
         kwargs['start_date'] = returned_start_time.strftime('%Y-%m-%d')
      return redirect('Habit:tracking_page', **kwargs)
      
         

      

   
   

templates/habit_tracks/description_form.html
<form method="POST" class="hidden mt-5" id="description_form">
   {% csrf_token %}
   <div class="mb-4">
      <label for="{{ form.description.id_for_label }}" class="font-bold">Description</label>
      {{ form.description }}
   </div>
   <div>
      <button class="bg-sky-800 rounded-sm px-5 py-2 text-sm font-semibold transition-all hover:bg-sky-700">Edit!</button>
      <button type="button" class="bg-slate-700 rounded-sm px-5 py-2 text-sm font-semibold transition-all cursor-pointer hover:bg-slate-600">Cancel</button>
   </div>
</form>

templates/habit_tracks/index.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}
<div class="w-11/12 md:w-5/6 mx-auto py-28">
   <div class="flex justify-between mb-16">
      <h1 class="font-semibold text-4xl">Habit List</h1>
      <button class="bg-sky-800 rounded-sm px-6 py-2 text-sm text-slate-200 transition-all hover:scale-[1.01] hover:bg-sky-700 hover:text-white" id="new_habit_btn">Add New Habit To Track</button>
   </div>
   <div class="md:flex flex-wrap justify-between">
      {% for habit in habits %}
      <a href="{% url 'Habit:tracking_page' user.username habit.name monday|date:'Y-m-d' %}" class="w-full sm:w-5/6 md:w-[49%] bg-slate-800 border border-slate-400 rounded-md mb-5 p-7 cursor-pointer transition-all hover:shadow-box-hover hover:scale-[1.02]">
         <h1 class="font-semibold mb-2">
            <span class="text-2xl">{{ habit.name }}</span>
            <span class="text-slate-200 pl-3">{{ habit.habit_type }}</span>
         </h1>
         <p class="text-[13px] text-slate-200 italic">{{ habit.description }}</p>
      </a>
      {% endfor %}
      {% if habits|length == 0 %}
      <p>No habit is found. Please create one and it will showed up here.</p>
      {% endif %}
   </div>
</div>

<div class="fixed top-0 left-0 w-full min-h-screen z-[90] hidden justify-center items-center" id="habit_form">
   <div class="absolute z-[100] w-[477px] bg-slate-800 rounded-lg px-7 py-10 opacity-0 -translate-y-24 transition-all duration-500" id="form">
      <h1 class="font-semibold text-[27px] mb-5">Add New Habit</h1>
      <form method="POST">
         {% csrf_token %}
         <div class="mb-4">
            <label for="{{ form.name.id_for_label }}" class="font-semibold">Habit Name:</label>
            {{ form.name }}
            <small class="text-red-400">{{ form.name.errors }}</small>
         </div>
         <div class="mb-4">
            <label for="{{ form.habit_type.id_for_label }}" class="font-semibold">Habit Type:</label>
            {{ form.habit_type }}
            <div class="relative">
               <div class="w-full bg-transparent border border-slate-600 rounded-sm mt-2 mb-1 p-2 text-sm text-slate-300 cursor-pointer" id="habit_type_input">
                  Select Type</div>
               <div class="hidden absolute top-full left-0 w-full bg-slate-700 text-sm border-t border-x border-slate-800 rounded-md opacity-0 -translate-y-5 cursor-pointer transition-all duration-300" id="habit_type_select">
                  <span class="block w-full border-b border-slate-800 p-3">Self-Improvement</span>
                  <span class="block w-full border-b border-slate-800 p-3">Ritual</span>
                  <span class="block w-full border-b border-slate-800 p-3">Killing Bad Habits</span>
                  <span class="block w-full border-b border-slate-800 p-3">Family</span>
               </div>
            </div>
            <small class="text-red-400">{{ form.habit_type.errors }}</small>
         </div>
         <div class="mb-4">
            <label for="{{ form.description.id_for_label }}" class="font-semibold">Habit Description:</label>
            {{ form.description }}
            <small class="text-red-400">{{ form.description.errors }}</small>
         </div>
         <div class="flex justify-end">
            <button class="border border-slate-600 rounded-sm px-5 py-2 text-sm transition-all hover:bg-slate-700">Create!!</button>
         </div>
      </form>
   </div>
   <div class="fixed w-full top-0 min-h-screen bg-neutral-900 opacity-0 transition-all duration-300 dark_bg"></div>
</div>
{% endblock %}

templates/habit_tracks/tracking_page.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}

{% load static %}
{% load custom_tags %}

<div class="border-b-2 border-slate-700">
   <div class="w-11/12 md:w-5/6 mx-auto pt-28 pb-10" id="habit_info">
      <h1 class="font-semibold text-2xl md:text-3xl lg:text-4xl">{{ habit_tracked.name }}</h1>
      <p class="w-2/3 my-4 text-slate-200 text-[13px] md:text-sm lg:text-base italic">{{ habit_tracked.description }}</p>
      {% include 'habit_tracks/description_form.html' %}
      <button class="bg-sky-800 rounded-sm px-5 py-2 text-sm font-semibold transition-all hover:bg-sky-700" id="edit_description_button">Edit Description</button>
   </div>
</div>

<div class="w-11/12 md:w-5/6 mx-auto pt-12 pb-24">
   <div class="md:flex justify-between items-center">
      <div class="mb-5 md:mb-0">
         <a href="{% url 'Habit:tracking_page' user.username habit_tracked.name today_timeframe|date:'Y-m-d' %}" 
            class="{% if timeframe_type == 'Weekly' %} bg-sky-800 {% else %} bg-slate-800 {% endif %} 
            border border-sky-900 rounded-full px-5 py-2 text-[13px] md:text-sm">Weekly</a>
         <a href="{% url 'Habit:tracking_page' user.username habit_tracked.name today_timeframe|date:'Y-m' %}"
            class="{% if timeframe_type == 'Monthly' %} bg-sky-800 {% else %} bg-slate-800 {% endif %} 
            border border-sky-900 rounded-full px-5 py-2 text-[13px] md:text-sm ml-2">Monthly</a>
      </div>
      <div class="flex items-center gap-5">
         <p class="font-bold md:text-lg">Timeline <span class="ml-3">:</span></p>
         <div class="relative">
            <div id="timeline_input" class="bg-sky-950 border border-sky-900 rounded-sm p-2 md:p-3 pr-16 md:pr-16 font-semibold text-[13px] md:text-sm cursor-pointer">{{ current_timeframe }}</div>
            <div id="timeline_select" class="absolute hidden top-full left-0 w-full max-h-[250px] overflow-auto z-10 bg-[#0a3857] rounded-sm text-[13px] md:text-sm opacity-0 -translate-y-5 transition duration-500 with-custom-scrollbar">
               {% if timeframe_type == 'Weekly' %}
               <div class="timline_select_option">
                  {% for weektime in weekly_menu %}
                  <a href="{% url 'Habit:tracking_page' user.username habit_tracked.name  weektime.monday|date:'Y-m-d' %}" class="block border-b border-sky-800 p-3 hover:bg-sky-950">{{ weektime.monday|date:'j F Y' }} - {{ weektime.sunday|date:'j F Y' }}</a>
                  {% endfor %}
               </div>
               {% elif timeframe_type == 'Monthly' %}
               <div class="timline_select_option">
                  {% for month_time in monthly_menu %}
                  <a href="{% url 'Habit:tracking_page' user.username habit_tracked.name  month_time|date:'Y-m' %}" class="block border-b border-sky-800 p-3 hover:bg-sky-950">{{ month_time|date:'F Y' }}</a>
                  {% endfor %}
               </div>
               {% endif %}
            </div>
         </div>
      </div>
   </div>
   <p class="text-xs text-slate-200 p-3 pb-0">Click the box to check your habits. (Can only be done for today's and yesterday's check)</p>


   {% if timeframe_type == 'Weekly' %}
   <div class="flex justify-center gap-3 flex-wrap mt-10 transition-all duration-200 tracks_wrapper" id="weekly_tracks">
      {% with ''|center:7 as range %}
      {% for x in range %}
      <div class="relative flex items-center justify-center min-w-[130px] md:min-w-[145px] max-w-[150px] overflow-hidden border border-slate-600 rounded-md py-12 md:py-14 font-bold md:text-lg
      {% if forloop.counter0 == today_day_index or forloop.counter == today_day_index %}
         activate_form
      {% endif %}
      {% if forloop.counter0 <= today_day_index %}
         {% if day_num_start|add:forloop.counter0 in habit_checks %}
            bg-sky-600
         {% else %}
            {% if forloop.counter0 == today_day_index %}
               {% if is_checked %}
                  bg-slate-600
               {% else %}
                  bg-slate-800
               {% endif %}
            {% else %}
               bg-slate-600
            {% endif %}
         {% endif %} 
      {% else %} bg-neutral-900
      {% endif %} transition-all hover:scale-[1.12] cursor-pointer">
         {% if forloop.counter0 == today_day_index or forloop.counter == today_day_index %}
         <div class="absolute -translate-y-[100px] transition-all duration-500">
            <form action="{% url 'Habit:check_habit' user.username habit_tracked.name %}" method="POST">
               {% csrf_token %}
               <input type="text" class="hidden" value="{{ day_num_start|add:forloop.counter0 }}" name="day_num">
               {% if day_num_start|add:forloop.counter0 in habit_checks %}
               <button type="button" class="bg-green-400 border-2 border-white rounded-full p-3"><img src="{% static '/image/check.png' %}" class="w-4 filter-to-white"></button>
               {% else %}
               <button name="check" class="border-2 border-white rounded-full p-3 hover:bg-slate-700"><img src="{% static '/image/check.png' %}" class="w-4 filter-to-white"></button>
               {% endif %}
               <button name="uncheck" class="border-2 border-white rounded-full p-3 hover:bg-slate-700"><img src="{% static '/image/cross.png' %}" class="w-4 filter-to-white"></button>
            </form>
         </div>
         {% endif %}
         <p class="absolute transition-all duration-500">{{ forloop.counter0|get_day_name }}</p>
      </div>
      {% endfor %}
      {% endwith %}
   </div>
   {% endif %}

   {% if timeframe_type == 'Monthly' %}
   <div class="flex justify-center gap-7 md:gap-5 lg:gap-3 flex-wrap mt-10 transition-all duration-200 tracks_wrapper" id="monthly_tracks">
      {% with ''|center:31 as range %}
      {% for _ in range %}
      <div class="relative flex items-center justify-center min-h-[80px] max-h-[81px] md:min-w-[125px] md:max-w-[126px] aspect-square overflow-hidden border border-slate-600 rounded-md font-bold md:text-lg
      {% if forloop.counter0 == today_day_index or forloop.counter == today_day_index %}
         activate_form
      {% endif %}

      {% if forloop.counter0 <= today_day_index %}
         {% if day_num_start|add:forloop.counter0 in habit_checks %}
            bg-sky-600
         {% else %}
            {% if forloop.counter0 == today_day_index %}
               {% if is_checked %}
                  bg-slate-600
               {% else %}
                  bg-slate-800
               {% endif %}
            {% else %}
               bg-slate-600
            {% endif %}
         {% endif %} 
      {% else %} bg-neutral-900
      {% endif %} transition-all hover:scale-[1.12] cursor-pointer">
         {% if forloop.counter0 == today_day_index or forloop.counter == today_day_index %}
         <div class="absolute -translate-y-[100px] transition-all duration-500">
            <form action="{% url 'Habit:check_habit' user.username habit_tracked.name %}" method="POST">
               {% csrf_token %}
               <input type="text" class="hidden" value="{{ day_num_start|add:forloop.counter0 }}" name="day_num">
               <input type="text" class="hidden" value="test" name="is_monthly">
               {% if day_num_start|add:forloop.counter0 in habit_checks %}
               <button type="button" class="bg-green-400 border-2 border-white rounded-full p-3"><img
                     src="{% static '/image/check.png' %}" class="w-4 filter-to-white"></button>
               {% else %}
               <button name="check" class="border-2 border-white rounded-full p-3 hover:bg-slate-700"><img
                     src="{% static '/image/check.png' %}" class="w-4 filter-to-white"></button>
               {% endif %}
               <button name="uncheck" class="border-2 border-white rounded-full p-3 hover:bg-slate-700"><img
                     src="{% static '/image/cross.png' %}" class="w-4 filter-to-white"></button>
            </form>
         </div>
         {% endif %}
         <p class="absolute transition-all duration-500">{{ forloop.counter }}</p>
      </div>
      {% endfor %}
      {% endwith %}
   </div>
   {% endif %}
</div>

{% if messages %}
{% for message in messages %}
   {% with message|jsonify as flash_mess %}
   {% if flash_mess.date is not None %}
      <div class="fixed flex justify-center items-center top-0 left-0 w-full min-h-screen z-[100]" id="check_flash_wrapper">
         <div class="fixed w-full h-full bg-neutral-900 opacity-50 transition-all" id="dark_bg"></div>
         <div class="relative w-[400px] z-10 bg-sky-950 rounded-xl shadow-box-hover transition-all duration-300 animate-appear" id="main_message">
            <img src="{% static 'image/cross.png' %}" class="absolute top-4 right-4 w-4 cursor-pointer filter-to-gray" id="close_button">
            <div class="border-b border-slate-300 text-center pt-10 pb-7">
               <h1 class="italic font-bold text-xl lg:text-2xl">Capri Tracks</h1>
            </div>
            <div class="px-10 py-14 pt-7">
               <p class="italic mb-3 text-slate-200 text-sm">Congratulation!! Thank to yourself because you have been consistent on doing/not-doing this habit!!</p>
               <p class="text-3xl">🥳🥳🎉🎊</p>
               <p class="mt-3 font-semibold">Date Completed: {{ flash_mess.date }}</p>
            </div>
         </div>
      </div>
      {% endif %}
      {% endwith %}
{% endfor %}
{% endif %}

{% endblock %}