habit_track/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import HabitIndexPage, HabitTrackingPage, CheckHabit

app_name = "Habit"
urlpatterns = [
   path('', HabitIndexPage.as_view(), name="main"),
   path('<str:username>/<str:slug>/check_habit', CheckHabit.as_view(), name='check_habit'),
   path('<str:username>/<str:slug>/<start_date>', HabitTrackingPage.as_view(), name="tracking_page")
]

time_track/urls.py
from django.urls import path, reverse_lazy
from .views import TimeTrackView, DeleteTimeTrack, AddTimeTrack

app_name = "TimeTrack"
urlpatterns = [
   path('delete_track/<pk>/', DeleteTimeTrack.as_view(), name='delete'),
   path('add_track/', AddTimeTrack.as_view(), name='add'),
   path('<monday_date>/', TimeTrackView.as_view(), name='main'),
]

templates/index.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}
<div class="w-11/12 md:w-5/6 mx-auto min-h-screen flex items-center">
   <div class="w-full text-center">
      <h1 class="font-bold mb-3 text-[34px] leading-10 sm:text-4xl lg:text-[42px] xl:text-5xl text-balance">TRACK YOUR TIME AND HABITS WITH</h1>
      <h2 class="font-bold text-xl md:text-2xl lg:text-3xl">-- Capri Tracks --</h2>
      <div class="mt-8 italic text-slate-300 text-[13px] md:text-sm lg:text-[15px] text-balance">
         <p class="mb-1">Track your habit and time to make sure you are using it efficiently and staying productive. </p>
         <p>"Progress is not achieved by luck or accident, but by working on yourself daily"</p>
         <p>-- Epictetus --</p>
      </div>
      <a href="{% url 'Habit:main' %}" class="inline-block border border-slate-500 rounded-sm mt-6 px-10 py-2 font-semibold text-sm md:text-base lg:text-lg text-slate-500 transition-all hover:bg-slate-800 hover:text-white hover:scale-105 hover:shadow-2xl hover:shadow-[#161E3B]">Start Tracking</a>
   </div>
</div>
{% endblock %}

templates/layout.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{% block title %}{% endblock %}</title>

   <!-- google font -->
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet">
   <!-- google font -->

   <!-- CSS and JS -->
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <script src="{% static 'js/jquery.js' %}"></script>
   <script src="{% static 'js/script.js' %}"></script>
</head>
<body class="bg-slate-900 text-white font-main">

   {% include 'navbar.html' %}

   {% block content %}{% endblock %}

   {% if messages %}
   {% for message in messages %}
      {% with message|jsonify as flash_mess %}
      {% if flash_mess.date is None %}
      <div class="fixed bottom-10 right-5 w-[400px] bg-slate-900 border border-slate-600 rounded-md animate-flash-mess translate-y-[200px]">
         <div class="px-4 md:px-5 py-3 border-b border-slate-600">
            <h1 class="text-[13px] md:text-sm font-semibold text-slate-100">{{ flash_mess.title }}</h1>
         </div>
         <div class="px-4 md:px-5 py-3">
            <p class="text-[11px] md:text-xs italic text-slate-300">{{ flash_mess.content }}</p>
         </div>
      </div>
      {% endif %}
      {% endwith %}
   {% endfor %}
   {% endif %}
   
   
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="fixed w-full h-[69px] z-[75] flex items-center bg-slate-900 border-b-2 border-slate-800 shadow-2xl shadow-[#161E3B]" id="main_nav">
   <div class="w-11/12 md:w-5/6 mx-auto flex items-center justify-between">
      <div class="flex items-center gap-12 lg:gap-20">
         <h1 class="italic font-bold text-xl lg:text-2xl"><a href="{% url 'home' %}">Capri Tracks</a></h1>
         <div class="hidden md:flex gap-5 lg:gap-10 font-semibold">
            <a href="{% url 'Habit:main' %}">Habit Tracks</a>
            <a href="{% url 'TimeTrack:main' monday_date %}">Time Tracks</a>
         </div>
      </div>
      <div class="hidden md:flex gap-3 text-slate-400 text-[15px]">
         {% if user.is_authenticated %}
         <a href="{% url 'profile' %}" class="flex items-center gap-2 border border-slate-600 rounded-sm px-4 lg:px-5 py-2 text-sm lg:text-base transition-all hover:bg-slate-800">
            <img src="{% static 'image/register.png' %}" class="hidden md:block w-3 lg:w-4 h-3 lg:h-4 filter-to-gray">
            <span>Profile</span>
         </a>
         <a href="{% url 'logout' %}" class="flex items-center gap-2 border border-slate-600 rounded-sm px-4 lg:px-5 py-2 text-sm lg:text-base transition-all hover:bg-slate-800">
            <img src="{% static 'image/login.png' %}" class="hidden md:block w-3 lg:w-4 h-3 lg:h-4 filter-to-gray">
            <span>Logout</span>
         </a>
         {% else %}
         <a href="{% url 'register' %}" class="flex items-center gap-2 border border-slate-600 rounded-sm px-4 lg:px-5 py-2 text-sm lg:text-base transition-all hover:bg-slate-800">
            <img src="{% static 'image/register.png' %}" class="hidden md:block w-3 lg:w-4 h-3 lg:h-4 filter-to-gray">
            <span>Register</span>
         </a>
         <a href="{% url 'login' %}" class="flex items-center gap-2 border border-slate-600 rounded-sm px-4 lg:px-5 py-2 text-sm lg:text-base transition-all hover:bg-slate-800">
            <img src="{% static 'image/login.png' %}" class="hidden md:block w-3 lg:w-4 h-3 lg:h-4 filter-to-gray">
            <span>Login</span>
         </a>
         {% endif %}
      </div>
      <div class="h-8 w-8 flex md:hidden flex-col justify-evenly cursor-pointer group" id="hamburger_btn">
         <div class="h-1 w-full bg-slate-700 rounded-full group-hover:bg-slate-600"></div>
         <div class="h-1 w-full bg-slate-700 rounded-full group-hover:bg-slate-600"></div>
         <div class="h-1 w-full bg-slate-700 rounded-full group-hover:bg-slate-600"></div>
      </div>
   </div>
</nav>
<nav class="fixed w-full z-[90] top-0 left-0 hidden md:hidden" id="nav_sm">
   <div class="absolute w-full z-[95] bg-slate-800 -translate-y-full transition-all duration-700" id="main_menu_navbar">
      <img src="{% static 'image/cross.png' %}" class="fixed top-8 right-8 w-6 h-6 filter-to-gray cursor-pointer hover:scale-95 transition-all" id="close_navbar">
      <div class="border-b border-slate-600 p-10">
         <h1 class="font-bold mb-6">Main Menu</h1>
         <ul class="text-[15px] pl-8">
            <li class="mb-6"><a href="{% url 'Habit:main' %}" class="flex items-center gap-3">
               <img src="{% static 'image/habit_track.png' %}" class="w-5 h-5 filter-to-gray">
               <span>Habit Tracks</span>
            </a></li>
            <li class="mb-6"><a href="" class="flex items-center gap-3">
               <img src="{% static 'image/time_track.png' %}" class="w-5 h-5 filter-to-gray">
               <span>Time Tracks</span>
            </a></li>
         </ul>
      </div>
      <div class="p-10">
         <h1 class="font-bold mb-6">Sub Menu</h1>
         <ul class="text-[15px] pl-8">
            {% if user.is_authenticated %}
            <li class="mb-6"><a href="{% url 'profile' %}" class="flex items-center gap-3">
               <img src="{% static 'image/register.png' %}" class="w-5 h-5 filter-to-gray">
               <span>Profile</span>
            </a></li>
            <li class="mb-6"><a href="{% url 'logout' %}" class="flex items-center gap-3">
               <img src="{% static 'image/login.png' %}" class="w-5 h-5 filter-to-gray">
               <span>Logout</span>
            </a></li>
            {% else %}
            <li class="mb-6"><a href="{% url 'register' %}" class="flex items-center gap-3">
               <img src="{% static 'image/register.png' %}" class="w-5 h-5 filter-to-gray">
               <span>Register</span>
            </a></li>
            <li class="mb-6"><a href="{% url 'login' %}" class="flex items-center gap-3">
               <img src="{% static 'image/login.png' %}" class="w-5 h-5 filter-to-gray">
               <span>Login</span>
            </a></li>
            {% endif %}
         </ul>
      </div>
   </div>
   <div class="fixed w-full top-0 min-h-screen bg-neutral-900 opacity-0 transition-all duration-300 dark_bg"></div>
</nav>

templates/temptation_cross.html
{% extends 'layout.html' %}
{% block title %}Temptation Cross{% endblock %}

{% block content %}
<div class="w-11/12 mx-auto py-24">
   <h1 class="mt-10 text-4xl text-center font-bold">TEMPTATION CROSS</h1>
   <div class="flex flex-wrap gap-3 justify-evenly mt-20">
      {% with ''|center:156 as range %}
      {% for _ in range %}
         {% if forloop.counter <= 8 %}
         <div class="flex justify-center items-center w-20 h-20 border-[3px] border-green-600 bg-green-600 rounded-lg select-none cursor-pointer">
            <h1 class="text-4xl text-white font-bold">{{ forloop.counter }}</h1>
         </div>
         {% else %}
         <div class="flex justify-center items-center w-20 h-20 border-[3px] border-slate-700 rounded-lg select-none cursor-pointer">
            <h1 class="text-4xl font-bold">{{ forloop.counter }}</h1>
         </div>
         {% endif %}
      {% endfor %}
      {% endwith %}
   </div>
</div>
{% endblock %}