habit_track/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import HabitIndexPage, HabitTrackingPage, CheckHabit

app_name = "Habit"
urlpatterns = [
   path('', HabitIndexPage.as_view(), name="main"),
   path('<str:username>/<str:slug>/check_habit', CheckHabit.as_view(), name='check_habit'),
   path('<str:username>/<str:slug>/<start_date>', HabitTrackingPage.as_view(), name="tracking_page")
]

time_track/urls.py
from django.urls import path, reverse_lazy
from .views import TimeTrackView, DeleteTimeTrack, AddTimeTrack

app_name = "TimeTrack"
urlpatterns = [
   path('delete_track/<pk>/', DeleteTimeTrack.as_view(), name='delete'),
   path('add_track/', AddTimeTrack.as_view(), name='add'),
   path('<monday_date>/', TimeTrackView.as_view(), name='main'),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
   class Meta:
      model = User
      fields = ["username", "email", "password1", "password2"]

class LoginForm(forms.Form):
   email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(attrs={
      'class': 'w-full bg-transparent border border-slate-500 rounded-sm mt-1 p-2 text-[13px] md:text-sm outline-none'
   }))
   password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
      'class': 'w-full bg-transparent border border-slate-500 rounded-sm mt-1 p-2 text-[13px] md:text-sm outline-none'
   }))

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.views.generic import View, RedirectView, TemplateView
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from habit_track.models import Habit
from time_track.models import TimeTrack
from .forms import RegistrationForm, LoginForm
from datetime import date, timedelta
import json, math

# Create your views here.
class RegisterUser(View):
   template_name = 'user/register.html'
   context = {
      "form": RegistrationForm
   }

   def get(self, request):
      if request.user.is_authenticated:
         return redirect('Habit:main')
      return render(request, self.template_name, self.context)

   def post(self, request):
      form = RegistrationForm(request.POST)

      if form.is_valid():
         form.save()
         
         message_dict = {
            "title": "Account Created",
            "content": "Your account is successfully created, you can now log in!!"
         }
         messages.success(request, json.dumps(message_dict))

         return redirect('login')

      return render(request, self.template_name, {
         "form": form
      })

class LoginUser(View):
   template_name = "user/login.html"
   context = {
      "form": LoginForm
   }

   def get(self, request):
      if request.user.is_authenticated:
         return redirect('Habit:main')
      return render(request, self.template_name, self.context)

   def post(self, request):
      form = LoginForm(request.POST)

      if form.is_valid():
         
         # check if user is found with email
         user = User.objects.filter(email=form.cleaned_data['email']).first()
         if user is not None:
            # check if password is correct
            if check_password(form.cleaned_data['password'], user.password):
               login(request, user)

               message_dict = {
                  "title": "Logging In",
                  "content": "You have logged in to your account! Please enjoy the app."
               }
               messages.success(request, json.dumps(message_dict))

               return redirect('Habit:main')

         message_dict = {
            "title": "Login Error",
            "content": "Your email or password is incorrect. Please check your spelling!"
         }
         messages.error(request, json.dumps(message_dict))
         return redirect('login')

      return render(request, self.template_name, self.context)


class LogoutPage(RedirectView, LoginRequiredMixin):
   def get(self, request, *args, **kwargs):
      logout(request)

      message_dict = {
         "title": "Logout Successful",
         "content": "You have successfully logged out from this account!"
      }
      messages.success(request, json.dumps(message_dict))

      return redirect('login')


class ProfilePage(TemplateView, LoginRequiredMixin):
   template_name = "user/profile.html"

   def get_time_track(self, chart_type):
      time_track = None
      match chart_type:
         case "Today":
            time_track = TimeTrack.objects.filter(date_for=date.today())
         case "Last 7 Days":
            start_date = (date.today() - timedelta(days=6)).strftime('%Y-%m-%d')
            time_track = TimeTrack.objects.filter(date_for__range=[start_date, date.today().strftime('%Y-%m-%d')])
         case "Previous 7 Days":
            start_date = (date.today() - timedelta(days=13)).strftime('%Y-%m-%d')
            end_date = (date.today() - timedelta(days=7)).strftime('%Y-%m-%d')
            time_track = TimeTrack.objects.filter(date_for__range=[start_date, end_date])
         case "Last 30 Days":
            start_date = (date.today() - timedelta(days=29)).strftime('%Y-%m-%d')
            time_track = TimeTrack.objects.filter(date_for__range=[start_date, date.today().strftime('%Y-%m-%d')])
         case "Previous 30 Days":
            start_date = (date.today() - timedelta(days=59)).strftime('%Y-%m-%d')
            end_date = (date.today() - timedelta(days=30)).strftime('%Y-%m-%d')
            time_track = TimeTrack.objects.filter(date_for__range=[start_date, end_date])
      
      return time_track

   def process_progress(self, chart_type):
      time_track = self.get_time_track(chart_type)

      productive_time_spent = 0
      unproductive_time_spent = 0
      neutral_time_spent = 0
      for track in time_track:
         match track.level:
            case "Productive": 
               productive_time_spent += track.time
            case "Unproductive": 
               unproductive_time_spent += track.time
            case "Neutral": 
               neutral_time_spent += track.time
      total_time = productive_time_spent + unproductive_time_spent + neutral_time_spent
      if total_time == 0: total_time = 1
      unproductive_percentage = math.ceil((unproductive_time_spent / total_time) * 100)
      neutral_percentage = math.ceil((neutral_time_spent / total_time) * 100)
      productive_percentage = 100 - unproductive_percentage - neutral_percentage

      return {
         'type': chart_type,
         'productive_with_neutral': productive_percentage,
         'unproductive_with_neutral': unproductive_percentage,
         'productive_without_neutral': productive_percentage + (neutral_percentage / 2),
         'unproductive_without_neutral': unproductive_percentage + (neutral_percentage / 2),
         'neutral': neutral_percentage
      }
   
   def get(self, request):
      habits = Habit.objects.all()

      productivity_progress_type = ["Today", "Last 7 Days", "Previous 7 Days", "Last 30 Days", "Previous 30 Days"]
      productivity_progress = []
      for progress_type in productivity_progress_type:
         productivity_progress.append(self.process_progress(progress_type))

      context = {
         "habits": habits,
         "productivity_progress": productivity_progress,
         'monday': date.today() - timedelta(days=date.today().weekday())
      }
      
      return render(request, self.template_name, context)



      

templates/user/login.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}
<div class="w-11/12 md:w-5/6 mx-auto min-h-screen flex items-center">
   <form method="post" class="w-[400px] md:w-[450px] mx-auto text-sm md:text-base">
      {% csrf_token %}
      <h1 class="mb-4 font-semibold text-2xl md:text-3xl text-center">LOGIN</h1>
      <div class="mb-4">
         <label for="{{ form.email.id_for_label }}">Email: </label>
         {{ form.email }}
         <small class="text-red-400">{{ form.email.errors }}</small>
      </div>
      <div class="mb-4">
         <label for="{{ form.password.id_for_label }}">Password: </label>
         {{ form.password }}
         <small class="text-red-400">{{ form.password.errors }}</small>
      </div>
      <div class="flex justify-end">
         <button class="inline-block border border-slate-500 rounded-sm mt-2 px-10 py-2 font-semibold text-sm text-slate-500 transition-all hover:bg-slate-800 hover:text-white hover:scale-105 hover:shadow-2xl hover:shadow-[#161E3B]">Login</button>
      </div>
   </form>
</div>
{% endblock %}

templates/user/profile.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}

{% load static %}
{% load custom_tags %}

<div class="pt-32 pb-16 border-b border-slate-700">
   <div class="w-11/12 md:w-5/6 mx-auto flex justify-between">
      <div>
         <h1 class="mb-2 font-bold text-5xl">{{ user.username }}</h1>
         <p class="text-slate-200">{{ user.email }}</p>
         <p class="text-slate-200 italic">Date Joined: {{ user.date_joined|date:'j F Y' }}</p>
      </div>
      <div class="pt-5">
         <button class="bg-slate-800 border border-slate-600 px-5 py-2 text-sm transition-all hover:bg-sky-900 hover:border-sky-700 hover:shadow-box-hover">Check Time Spent</button>
      </div>
   </div>
</div>
<div class="w-11/12 md:w-5/6 mx-auto py-16">
   <div>
      <h1 class="font-semibold text-2xl md:text-3xl mb-7">Your Productivity Time Progress</h1>
      <table class="w-full">
         <thead>
            <tr class="border-b border-slate-400">
               <td class="font-semibold p-3">No</td>
               <td class="font-semibold p-3">Habit Name</td>
               <td class="font-semibold p-3">Created Date</td>
               <td class="font-semibold p-3 text-center">Detail</td>
            </tr>
         </thead>
         <tbody>
            {% for habit in habits %}
            <tr class="border-b border-slate-700">
               <td class="p-4">{{ forloop.counter }}</td>
               <td class="p-4">{{ habit.name }}</td>
               <td class="p-4">{{ habit.created_at|date:'j F Y' }}</td>
               <td class="text-center p-4"><a href="{% url 'Habit:tracking_page' user.username habit.name monday|date:'Y-m-d' %}" class="bg-slate-800 border border-slate-600 px-5 py-2 text-sm transition-all hover:bg-[#233046]">Detail</a></td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
   </div>
   <div class="mt-24">
      <div class="md:flex gap-5 justify-between items-center mb-10">
         <h1 class="font-semibold text-2xl md:text-3xl mb-4 md:mb-0">Your Productivity Time Progress</h1>
         <button class="relative flex gap-2 items-center justify-center bg-slate-800 border border-slate-600 rounded-md w-40 md:w-48 py-3 text-sm transition-all hover:bg-[#233046]" id="show_color_info">
            <img src="{% static 'image/info.png' %}" class="w-5 filter-to-gray">
            <span class="font-semibold">Color Info</span>

            <div class="absolute top-full left-0 md:left-auto md:right-0 translate-y-3 bg-slate-700 rounded-md p-5 hidden opacity-0 scale-90 transition-all duration-300">
               <div class="flex gap-2 items-center mb-3 pr-3">
                  <div class="w-6 h-6 bg-[#22c55e]"></div>
                  <p>Productive</p>
               </div>
               <div class="flex gap-2 items-center mb-3 pr-3">
                  <div class="w-6 h-6 bg-[#be123c]"></div>
                  <p>Unproductive</p>
               </div>
               <div class="flex gap-2 items-center pr-3">
                  <div class="w-6 h-6 bg-[#0369a1]"></div>
                  <p>Neutral</p>
               </div>
            </div>
         </button>
      </div>
      <div class="bg-slate-800 rounded-md p-10">
         <div class="flex justify-between mb-7">
            <div class="text-left text-xl md:text-2xl font-bold">Include Neutral Time</div>
            <div class="text-right text-lg sm:text-xl md:text-2xl font-bold">Exclude Neutral Time</div>
         </div>
         {% for pie_chart in productivity_progress %}
         <div class="mb-10">
            <div class="grid grid-cols-8 items-center justify-center">
               <div class="col-start-1 col-end-3">
                  <div class="w-24 h-24 md:w-28 md:h-28 mx-auto rounded-full pie_graph_representation" 
                  data-productive-percentage="{{ pie_chart.productive_with_neutral }}" 
                  data-unproductive-percentage="{{ pie_chart.unproductive_with_neutral }}"
                  data-neutral-percentage="{{ pie_chart.neutral }}"></div>
               </div>
               <div class="flex justify-evenly items-center gap-3 col-start-3 col-end-7">
                  <img src="{% static 'image/arrow.png' %}" class="hidden md:block w-5 h-5 filter-to-gray rotate-180">
                  <span class="font-semibold text-slate-300 text-[15px] md:text-base lg:text-lg">{{ pie_chart.type }}</span>
                  <img src="{% static 'image/arrow.png' %}" class="hidden md:block w-5 h-5 filter-to-gray">
               </div>
               <div class="col-start-7 col-end-9">
                  <div class="w-24 h-24 md:w-28 md:h-28 mx-auto rounded-full pie_graph_representation" 
                  data-productive-percentage="{{ pie_chart.productive_without_neutral }}" 
                  data-unproductive-percentage="{{ pie_chart.unproductive_without_neutral }}"></div>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</div>

{% include 'time_track/new_tracks.html' %}

{% endblock %}

templates/user/register.html
{% extends 'layout.html' %}
{% block title %}Welcome to Capri Tracks{% endblock %}

{% block content %}
<div class="w-11/12 md:w-5/6 mx-auto pt-32 pb-16">
   <form method="post" class="w-[400px] md:w-[450px] mx-auto text-sm md:text-base">
      {% csrf_token %}
      <h1 class="mb-4 font-semibold text-2xl md:text-3xl text-center">CREATE ACCOUNT</h1>
      <div class="mb-4">
         <label for="{{ form.username.id_for_label }}">Username: </label>
         <input type="text" id="{{ form.username.id_for_label }}" required autofocus name="{{ form.username.name }}" maxlength="150" class="w-full bg-transparent border border-slate-500 rounded-sm mt-1 p-2 text-[13px] md:text-sm outline-none" value="{% if form.username.value is not None %}{{ form.username.value }}{% endif %}">
         <small class="text-red-400">{{ form.username.errors }}</small>
      </div>
      <div class="mb-4">
         <label for="{{ form.email.id_for_label }}">Email: </label>
         <input type="text" id="{{ form.email.id_for_label }}" required name="{{ form.email.name }}" maxlength="254" class="w-full bg-transparent border border-slate-500 rounded-sm mt-1 p-2 text-[13px] md:text-sm outline-none" value="{% if form.email.value is not None %}{{ form.email.value }}{% endif %}">
         <small class="text-red-400">{{ form.email.errors }}</small>
      </div>
      <div class="mb-4">
         <label for="{{ form.password1.id_for_label }}">Password: </label>
         <input type="password" id="{{ form.password1.id_for_label }}" required name="{{ form.password1.name }}" class="w-full bg-transparent border border-slate-500 rounded-sm mt-1 p-2 text-[13px] md:text-sm outline-none">
         <small class="text-red-400">{{ form.password1.errors }}</small>
      </div>
      <div class="mb-4">
         <label for="{{ form.password2.id_for_label }}">Password Confirmation: </label>
         <input type="password" id="{{ form.password2.id_for_label }}" required name="{{ form.password2.name }}" class="w-full bg-transparent border border-slate-500 rounded-sm mt-1 p-2 text-[13px] md:text-sm outline-none">
         <small class="text-red-400">{{ form.password2.errors }}</small>
      </div>
      <div class="flex justify-end">
         <button class="inline-block border border-slate-500 rounded-sm mt-2 px-10 py-2 font-semibold text-sm text-slate-500 transition-all hover:bg-slate-800 hover:text-white hover:scale-105 hover:shadow-2xl hover:shadow-[#161E3B]">Create Account</button>
      </div>
   </form>
</div>
{% endblock %}